# Generated by Django 6.0.2 on 2026-03-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_help_rewarded',
            field=models.BooleanField(default=False, verbose_name='首次助人奖励已发放'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_reward_given',
            field=models.BooleanField(default=False, verbose_name='资料完善奖励已发放'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=0, verbose_name='信用积分'),
        ),
    ]
