# Generated by Django 6.0.2 on 2026-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_college_user_first_help_rewarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='task',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置名称'),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
