# Generated by Django 6.0.2 on 2026-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_latitude_task_location_name_task_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='任务图片'),
        ),
    ]
