# Generated by Django 6.0.2 on 2026-03-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='已被隐藏'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('task', '任务'), ('user', '用户')], max_length=10, verbose_name='举报对象类型')),
                ('target_id', models.IntegerField(verbose_name='被举报对象ID')),
                ('target_snapshot', models.JSONField(default=dict, verbose_name='被举报内容快照')),
                ('reason', models.CharField(choices=[('FAKE', '虚假信息'), ('FRAUD', '欺诈行为'), ('BAD_CONTENT', '不良内容'), ('HARASSMENT', '骚扰'), ('OTHER', '其他')], max_length=20, verbose_name='举报类型')),
                ('description', models.TextField(blank=True, verbose_name='举报说明')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='证据截图')),
                ('status', models.CharField(choices=[('PENDING', '审核中'), ('HANDLED', '已处理'), ('REJECTED', '已驳回')], default='PENDING', max_length=10, verbose_name='处理状态')),
                ('result_note', models.TextField(blank=True, verbose_name='管理员处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后处理时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '举报记录',
                'verbose_name_plural': '举报记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
