# Generated by Django 6.0.2 on 2026-03-18 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_is_hidden_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_college',
            field=models.CharField(blank=True, help_text='留空则全校可见', max_length=100, null=True, verbose_name='目标学院'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('SYSTEM', '系统通知'), ('TASK_ACCEPTED', '接单提醒'), ('TASK_COMPLETED', '任务完成'), ('TASK_CANCELLED', '任务取消'), ('NEW_MESSAGE', '新私信')], default='SYSTEM', max_length=20, verbose_name='通知类型')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('student_id_image', models.URLField(verbose_name='校园卡/学生证照片')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=15, verbose_name='审核状态')),
                ('note', models.TextField(blank=True, verbose_name='管理员审核说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '学生认证申请',
                'verbose_name_plural': '学生认证申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='评分(1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='被评价者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务评价',
                'verbose_name_plural': '任务评价',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'reviewer')},
            },
        ),
    ]
