# Generated by Django 6.0.2 on 2026-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_target_college_notification_verifyapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating_attitude',
            field=models.IntegerField(default=5, verbose_name='服务态度'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_communication',
            field=models.IntegerField(default=5, verbose_name='沟通交流'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_quality',
            field=models.IntegerField(default=5, verbose_name='完成质量'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_reliability',
            field=models.IntegerField(default=5, verbose_name='诚信可靠'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_speed',
            field=models.IntegerField(default=5, verbose_name='响应速度'),
        ),
    ]
