# Generated by Django 6.0.2 on 2026-03-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_review_rating_review_rating_attitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', '待接单'), ('PENDING_ACCEPT', '待同意接单'), ('IN_PROGRESS', '进行中'), ('PENDING_CONFIRM', '待确认'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='OPEN', max_length=20, verbose_name='状态'),
        ),
    ]
