# Generated by Django 6.0.2 on 2026-04-02 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN', '封禁用户'), ('HIDE', '隐藏任务'), ('APPROVE', '审核通过'), ('REJECT', '审核拒绝'), ('OTHER', '其他操作')], max_length=20, verbose_name='操作类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='目标ID(用户/任务/等业务主键)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('reason', models.TextField(blank=True, verbose_name='批注缘由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '管理员操作审计日志',
                'verbose_name_plural': '管理员操作审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
