# Generated by Django 6.0.2 on 2026-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('STUDY', '学业指导'), ('TRADE', '物品交易'), ('HELP', '生活协助')], db_index=True, max_length=20, verbose_name='任务分类'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已被隐藏'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', '待接单'), ('PENDING_ACCEPT', '待同意接单'), ('IN_PROGRESS', '进行中'), ('PENDING_CONFIRM', '待确认'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='OPEN', max_length=20, verbose_name='状态'),
        ),
    ]
